name: dartis
version: 0.6.0
author: Juan Mellado <jcmellado@gmail.com>
homepage: https://github.com/jcmellado/dartis
description: >-
  Redis client featuring type-safe commands, pipelining,
  fire and forget, publish/subscribe, monitor mode, inline
  commands, transactions, Lua scripting, modules, and much more.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  logging: ^1.0.1

dev_dependencies:
  test: ^1.14.2
  uuid: ^3.0.4
